apiVersion: v1
kind: PersistentVolume
metadata:
  name: pg-in-ubi8-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/data/pg-in-ubi8
